#!/bin/sh

set -e # exit on the first error

TOOLS_DIR=./tools
MOD_DIR=.

# A hack to get GitHub Desktop on Windows to behave (not necessary for Git CLI).
# This is where cygpath.exe should be located on Windows, assuming default Git install directory.
# Otherwise, GitHub Desktop users might need to manually add its actual location to PATH.
CYGPATH_PATH_GUESS=/c/Program\ Files/Git/usr/bin
export PATH=$PATH:$CYGPATH_PATH_GUESS

#
# Main
#

PYTHON_VENV_DIR=venv

if [ -n $PYTHON_VENV_DIR ]
then
    if [ -e $PYTHON_VENV_DIR/Scripts/activate ] # Windows
    then
        . $PYTHON_VENV_DIR/Scripts/activate
        trap deactivate EXIT
    elif [ -e $PYTHON_VENV_DIR/bin/activate ] # Linux or macOS
    then
        . $PYTHON_VENV_DIR/bin/activate
        trap deactivate EXIT
    fi
fi

which python > /dev/null
if [ $? -ne 0 ]
then
    >&2 printf "\nERROR: Python not installed or missing from PATH\n"
    exit 2
fi

which pip > /dev/null
if [ $? -ne 0 ]
then
    >&2 printf "\nERROR: pip not installed or missing from PATH\n"
    exit 3
fi

echo "Using $(python -V) at $(which python)"

if pip freeze -r "$TOOLS_DIR/tools/requirements.txt" 2>&1 1>/dev/null | grep -P "^WARNING:" > /dev/null
then
    >&2 printf "\nERROR: missing required Python dependencies\n"
    echo "To install them, run the following command from the root of the repo:"
    echo "pip install -r $TOOLS_DIR/requirements.txt"
    exit 4
fi

if ! "$TOOLS_DIR/compress_tga.py" --git-hook "$MOD_DIR/gfx/map/terrain/*.tga"
then
    >&2 printf "\nERROR: failed to compress map TGAs\n"
    exit 5
fi
