dummy_name_list = {
	cadet_dynasty_names = {
		{ "dynnp_of" "dynn_Viken" }
		{ "dynnp_of" "dynn_Vestfold" }
		{ "dynnp_of" "dynn_HardrA_de" }
		{ "dynnp_of" "dynn_Gille" }
		{ "dynnp_of" "dynn_Sverre" }
		"dynn_Brusastad"
		"dynn_Bolt"
		"dynn_Giske"
		"dynn_Raud"
		"dynn_Gullbjelke"
		"dynn_Hesby"
		{ "dynnp_av" "dynn_Sudreim" }
		{ "dynnp_av" "dynn_Norge" }
		"dynn_Ulfhilde"
		{ "dynnp_av" "dynn_Aurland" }
		"dynn_KormA_kur"
		"dynn_Gautur"
		"dynn_Kvaran"
		"dynn_EldjA_rn"
		"dynn_MjO_ll"
		"dynn_NO_tt"
		"dynn_BlO_ndal"
		"dynn_Finne"
		"dynn_Orri"
		"dynn_GrO_nske"
		"dynn_Nordal"
		"dynn_TrA_tte"
		"dynn_KjA_rnested"
		"dynn_BjO_rk2"
		"dynn_Dosenrode"
		"dynn_Haarde"
		"dynn_A_sbrning"
		"dynn_Oddaverjar"
		"dynn_Ormslev"
		"dynn_Gnarr"
		"dynn_Holmsen"
		"dynn_Benkestokk"
		"dynn_Handingmann"
		"dynn_Aspa"
		"dynn_Aurland"
		"dynn_BjarkO_y"
		"dynn_Andenes"
		"dynn_Blakar"
		"dynn_Blindheim"
		"dynn_Asdal"
		"dynn_Hudfat"
		"dynn_HA_rd"
		"dynn_Kane"
		"dynn_Losna"
		"dynn_Ringnes"
		"dynn_Semeleng"
		"dynn_SpA_nheim"
		"dynn_Gjesling"
		"dynn_Sudrheim"
		"dynn_Talgje"
		"dynn_Teiste"
		"dynn_O_stby"
		"dynn_O_strA_t"
		"dynn_Rein"
		"dynn_Giske"
		"dynn_Kamp"
		"dynn_Nordhagen"
		"dynn_Bolt"
		"dynn_Galle"
		"dynn_Galtung"
		"dynn_Hjerne"
		"dynn_Kamp"
		"dynn_RO_mer"
		"dynn_Skanke"
		"dynn_SmO_r"
		"dynn_Staur"
		"dynn_Skjegge"
		"dynn_Gunn"
		"dynn_Helmehytte"
		"dynn_Akeleye"
		"dynn_Brockenhuus"
		"dynn_Kamban"
		"dynn_Somerled"
		"dynn_MO_re"
		"dynn_Krabbe"
		"dynn_Lodehat"
		"dynn_Pagh"
		"dynn_Vedel"
		"dynn_Rosenkrantz"
		"dynn_Kaas"
		"dynn_Juel"
		"dynn_Bildt"
		"dynn_Galte"
		"dynn_Drotning"
		"dynn_Kjarval"
		"dynn_Ekeh"
		"dynn_LO_ve"
		"dynn_Ormstunga"
		"dynn_GoD_i"
		"dynn_Gautur"
		"dynn_Eyfells"
		"dynn_A_sgeir"
		"dynn_Kamban"
		"dynn_Braghde"
		"dynn_BanE_r"
		"dynn_Wrede"
		"dynn_Balk"
		"dynn_Taube"
		"dynn_Creutz"
		"dynn_Wrangel"
		"dynn_Sporre"
		"dynn_EhrensvA_rd"
		"dynn_Aldersparre"
		"dynn_AdelswA_rd"
		"dynn_Hlidarendi"
		"dynn_UI__I_mair"
		"dynn_O_stman"
		{ "dynnp_av" "dynn_Rogen" }
		{ "dynnp_av" "dynn_Bergen" }
		{ "dynnp_av" "dynn_Eidsborg" }
		{ "dynnp_av" "dynn_Finnmark" }
		{ "dynnp_av" "dynn_RO_st" }
		{ "dynnp_af" "dynn_Romerike" }
		"dynn_Dovre"
	}

	dynasty_names = {
		"dynn_Brusastad"
		"dynn_Bolt"
		"dynn_Giske"
		"dynn_Raud"
		"dynn_Gullbjelke"
		"dynn_Hesby"
		{ "dynnp_av" "dynn_Sudreim" }
		{ "dynnp_av" "dynn_Norge" }
		"dynn_Ulfhilde"
		{ "dynnp_av" "dynn_Aurland" }
		"dynn_KormA_kur"
		"dynn_Gautur"
		"dynn_Kvaran"
		"dynn_EldjA_rn"
		"dynn_MjO_ll"
		"dynn_NO_tt"
		"dynn_BlO_ndal"
		"dynn_Finne"
		"dynn_Orri"
		"dynn_GrO_nske"
		"dynn_Nordal"
		"dynn_TrA_tte"
		"dynn_KjA_rnested"
		"dynn_BjO_rk2"
		"dynn_Dosenrode"
		"dynn_Haarde"
		"dynn_A_sbrning"
		"dynn_Oddaverjar"
		"dynn_Ormslev"
		"dynn_Gnarr"
		"dynn_Holmsen"
		"dynn_Benkestokk"
		"dynn_Handingmann"
		"dynn_Aspa"
		"dynn_Aurland"
		"dynn_BjarkO_y"
		"dynn_Andenes"
		"dynn_Blakar"
		"dynn_Blindheim"
		"dynn_Asdal"
		"dynn_Hudfat"
		"dynn_HA_rd"
		"dynn_Kane"
		"dynn_Losna"
		"dynn_Ringnes"
		"dynn_Semeleng"
		"dynn_SpA_nheim"
		"dynn_Gjesling"
		"dynn_Sudrheim"
		"dynn_Talgje"
		"dynn_Teiste"
		"dynn_O_stby"
		"dynn_O_strA_t"
		"dynn_Rein"
		"dynn_Giske"
		"dynn_Kamp"
		"dynn_Nordhagen"
		"dynn_Bolt"
		"dynn_Galle"
		"dynn_Galtung"
		"dynn_Hjerne"
		"dynn_Kamp"
		"dynn_RO_mer"
		"dynn_Skanke"
		"dynn_SmO_r"
		"dynn_Staur"
		"dynn_Skjegge"
		"dynn_Gunn"
		"dynn_Helmehytte"
		"dynn_Akeleye"
		"dynn_Brockenhuus"
		"dynn_Kamban"
		"dynn_Somerled"
		"dynn_MO_re"
		"dynn_Krabbe"
		"dynn_Lodehat"
		"dynn_Pagh"
		"dynn_Vedel"
		"dynn_Rosenkrantz"
		"dynn_Kaas"
		"dynn_Juel"
		"dynn_Bildt"
		"dynn_Galte"
		"dynn_Drotning"
		"dynn_Kjarval"
		"dynn_Ekeh"
		"dynn_LO_ve"
		"dynn_Ormstunga"
		"dynn_GoD_i"
		"dynn_Gautur"
		"dynn_Eyfells"
		"dynn_A_sgeir"
		"dynn_Kamban"
		"dynn_Braghde"
		"dynn_BanE_r"
		"dynn_Wrede"
		"dynn_Balk"
		"dynn_Taube"
		"dynn_Creutz"
		"dynn_Wrangel"
		"dynn_Sporre"
		"dynn_EhrensvA_rd"
		"dynn_Aldersparre"
		"dynn_AdelswA_rd"
		"dynn_Hlidarendi"
		"dynn_UI__I_mair"
		"dynn_O_stman"
		{ "dynnp_av" "dynn_Rogen" }
		{ "dynnp_av" "dynn_Bergen" }
		{ "dynnp_av" "dynn_Eidsborg" }
		{ "dynnp_av" "dynn_Finnmark" }
		{ "dynnp_av" "dynn_RO_st" }
		{ "dynnp_af" "dynn_Romerike" }
		"dynn_Dovre"
	}
	
	male_names = {
		Anund Alv Arne Arnfinn Arnkjell Arnmod Arnvid Aslak Audun Balder BA_rd BjOErn Eigil Eilif Einar Eirik Erlend Erling Eystein Finn Frej
		Grim Gudbrand Gudleik Gudmund GudrOEd Gunnar Guttorm Haldor Halfdan Halkjell Harald Helge HA_kon HA_vard Inge Ivar Jon KA_re Kolbein Lodin
		Magnus Odd Ogmund Olav Orm Ossor Ottar PAAl Ragnar Ragnvald Rolf Sigurd Skjalg Skofte Skule Svein Sverre SA_mund TorbjOErn Tord Tore
		Torbrand Torfinn Torgeir Torgil
		Tormod Torolf Torstein Trond Tryggve Ulv Vigleik A_le A_mund O_lver O_ystein
	}
	female_names = {
		Anna Astrid Brigida Cecilia Eldrid Freja Gjertrud Gudrid Gudrun Gunnhild Gyda Gyrid Haldora Homlaug IngebjO_rg Ingjerd Ingrid Jorunn
		Karin Kristina Margrete Maria Martha Ragna Ragnfrid Ragnhild Rannveig Sigrid SnO_frid Sunniva Svanhild Thora Thorborg Thordis A_se A_shild A_sta
	}
	
	dynasty_of_location_prefix = "dynnp_av"
	
	patronym_suffix_male = "dynnpat_suf_sson"
	patronym_suffix_female = "dynnpat_suf_sdatter"
	always_use_patronym = yes	

	mercenary_names = {
		{ name = "mercenary_company_birchers_of_place" }
	}
}
